import { StyleSheet } from 'react-native';
import { ApplicationStyles, Colors, Fonts, Metrics} from '../../theme';

export default StyleSheet.create({
  ...ApplicationStyles.screen,
  container:{
    flex:1,
    flexDirection:"column",
    margin:15
  },
  submitButtonContainer:{
    marginTop:40,
    flex:0.2
  },
  submitButton:{
    width:Metrics.screenWidth/2,
    height:45,
    backgroundColor:Colors.transparent,
    borderRadius:22,
    marginBottom:0,
    alignSelf:"center"
  },
  submitButtonDefaultColor:{
    flex: 1,
    backgroundColor: Colors.transparent,
  },
  submitButtonText:{
    alignSelf:"center",
    marginTop:10,
    ...Fonts.style.regularFont,
    color:Colors.white
  },
  wishesBox:{
    flex:0.1,
    justifyContent:"center",
    alignItems:"center"
  },
  wishiesText:{
    ...Fonts.style.buttonText,
    color:Colors.black
  },
  underlineStyle:{
    flex:0.1,
    marginTop:30,
    height:1, width:Metrics.screenWidth/1.1,
    backgroundColor:Colors.thinLineColor,
    alignSelf:'center'
  },
  emotionsHeadingBox:{
    flex:0.2,
    alignSelf:"center",
    marginTop:30
  },
  emotionsHeadingText:{
    fontSize:Fonts.size.h5,
    color:Colors.black,
    fontFamily:Fonts.lato.light
  },
  emotionImageContainer:{
    flex:0.2,
    flexDirection:'row',
    alignSelf:'center',
    marginTop:20
  },
  imagesGap:{
    marginRight:25
  },
  improvementContainer:{
    flex:0.1,
    alignSelf:"center",
    marginTop:30
  },
  improvementText:{
    fontSize:Fonts.size.regular,
    fontFamily:Fonts.lato.light,
    color:Colors.black
  },
  feedbackButtonContainer:{
    flex:0.2,
    alignSelf:"center",
    flexDirection:'row',
    marginTop:30
  },
  serviceTextButton:{
    borderWidth:1,
    height:29,
    width:94,
    borderRadius:15,
    marginRight:5,
    borderColor:Colors.headingColor
  },
  behaviorTextButton:{
    borderWidth:1,
    height:29,
    width:94,
    borderRadius:15,
    marginRight:5,
    borderColor:Colors.headingColor
  },
  otherstextButton:{
    borderWidth:1,
    height:29,
    width:94,
    borderRadius:15,
    borderColor:Colors.headingColor
  },
  serviceText:{
    marginRight:-9,
    marginLeft:-5,
    ...Fonts.style.availabiltyNone,
    color:Colors.profileInputHeadingColor
  },
  behaviorText:{
    marginRight:-22,
    marginLeft:-12,
    ...Fonts.style.availabiltyNone,
    color:Colors.profileInputHeadingColor
  },
  othersText:{
    marginRight:-10,
    marginLeft:-5,
    ...Fonts.style.availabiltyNone,
    color:Colors.profileInputHeadingColor
  }


});
