// leave off @2x/@3x
const images = {
  logo: require('../images/logo.png'),
  introLocation: require('../images/location.png'),
  bag: require('../images/bag.png'),
  mobilelogo: require('../images/mobilelogo.png'),
  facebookIcon: require('../images/facebook.png'),
  googleIcon: require('../images/google.png'),
  edit: require('../images/edit.png'),
  home: require('../images/home.png'),
  profile: require('../images/profile.png'),
  travel: require('../images/travel.png'),
  setting: require('../images/setting.png'),
  travelActive: require('../images/travelActive.png'),
  profileActive: require('../images/profileActive.png'),
  settingActive: require('../images/settingActive.png'),
  homeActive: require('../images/homeActive.png'),
  name: require('../images/name.png'),
  mobile: require('../images/mobile.png'),
  password: require('../images/password.png'),
  email: require('../images/email.png'),
  dropdown:require('../images/dropdown.png'),
  arrowBack:require('../images/arrowBack.png'),
  arrowForward: require('../images/arrowForward.png'),
  leftArrow: require('../images/leftArrow.png'),
  rightArrow: require('../images/rightArrow.png'),
  offer: require('../images/offer.png'),
  googlePlus: require('../images/googlePlus.png'),
  fb: require('../images/fb.png'),
  whatsapp: require('../images/whatsapp.png'),
  notification: require('../images/notification.png'),
  roundtriphome: require('../images/roundtriphome.png'),
  roundtripunivercity: require('../images/roundtripuniversity.png'),
  roundtripinputicon: require('../images/roundtripinputicon.png'),
  roundtripaddicon: require('../images/add.png'),
  roundtripbusicon: require('../images/busIcon.png'),
  roundtriptrackicon: require('../images/track.png'),
};
export default images;
