import { StyleSheet } from 'react-native';
import { ApplicationStyles, Colors, Fonts, Metrics } from '../../theme';

export default StyleSheet.create({
  ...ApplicationStyles.screen,
  titleContainer:{
    marginTop:Metrics.screenHeight/14,
  },
  container:{
    flex:1,
    marginBottom:20
  },
  loginMedium:{
    flex:0.3,
    justifyContent:"center",
    alignItems:"center"
  },
  formInputs:{
    flex:0.5
  },
  titleTextStyle:{
    ...Fonts.style.buttonFont,
    justifyContent:'center',
    alignItems:'center',
    color:Colors.signupTitle
  },
  loginFacebookContainer:{
    marginTop:40,
  },
  loginFacebookButton:{
    alignItems:"center",
    justifyContent:"center",
    width:Metrics.screenWidth/1.4,
    height:45,
    backgroundColor:Colors.facebookButton,
    borderRadius:22,
    flexDirection:'row',
  },
  loginGoogleButton:{
    alignItems:"center",
    justifyContent:"center",
    width:Metrics.screenWidth/1.4,
    height:45,
    backgroundColor:Colors.googleButton,
    borderRadius:22,
    flexDirection:'row',
    marginTop:20,
  },
  facebookButtonText:{
    ...Fonts.style.buttonText,
    color:Colors.white,
  },
  googleButtonText:{
    ...Fonts.style.buttonText,
    color:Colors.white,
  },
  facebookButtonImage:{
    flex:0.2,
    alignItems:'center',
    justifyContent:'center',
    backgroundColor:Colors.facebookIconBg,
    height:45,
    borderTopLeftRadius: 22,
    borderBottomLeftRadius:22,
  },
  googleButtonImage:{
    flex:0.2,
    alignItems:'center',
    justifyContent:'center',
    backgroundColor:Colors.googleIconBg,
    height:45,
    borderTopLeftRadius: 22,
    borderBottomLeftRadius:22,
  },

  buttonText:{
    flex:0.9,
    alignItems:'flex-start',
    marginLeft:10,

  },
  facebookImage:{
    height:18,
    width:10,
  },
  googleImage:{
    height:17,
    width:17
  },
  optionalContainer:{
    flexDirection:'row',
    marginTop:Metrics.screenHeight/20,
  },
  optional:{
    ...Fonts.style.buttonText,
    color:Colors.options,
  },
  signupButton:{
    justifyContent:"center",
    alignItems:'center',
    borderWidth:1,
    borderColor:Colors.signupButtonText,
    borderRadius:22,
    height:45,
    width: Metrics.screenWidth/1.4,
  },
  signupButtonContainer:{
    flex:0.2,
    justifyContent:"center",
    alignItems:"center",
  },
  formContainer:{
    flexDirection:'column',
    marginTop:10,
    marginLeft:Metrics.screenWidth/8,
    marginRight:Metrics.screenWidth/8,
    marginBottom:20
  },
  signupText:{
    ...Fonts.style.signupButtonText,
    color:Colors.signupButtonText,
  },
  placeholderTextStyle:{
  },
  LoginHyperlink:{
    color:Colors.signupButtonText,
    ...Fonts.style.buttonText
  },
  formIcon:{
    marginRight:4,
  }


});
